name: Build and test LLDB

on:
  push:
  # Allows manual running from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true

    - name: Install SWIG
      run: sudo apt-get update && sudo apt-get install -y swig

    - name: Download dependencies
      run: ./download_dependencies.sh

    # Build

    - name: Build LLDB for host
      run: ./build_lldb.sh

    - name: Build lldb-server for Android arm64
      run: ANDROID_ABI=arm64-v8a ./build_lldb_server.sh

    - name: Build lldb-server for Android arm32
      run: ANDROID_ABI=armeabi-v7a ./build_lldb_server.sh

    - name: Build lldb-server for Android x86_64
      run: ANDROID_ABI=x86_64 ./build_lldb_server.sh

    # Upload

    - name: Upload LLDB for host
      uses: actions/upload-artifact@v4
      with:
        name: lldb-linux-x86_64-${{ github.run_id }}
        path: build-linux-x86_64/install/
        if-no-files-found: 'error'

    - name: Upload lldb-server for Android arm64
      uses: actions/upload-artifact@v4
      with:
        name: lldb-server-arm64-${{ github.run_id }}
        path: build-arm64-v8a/out/bin/lldb-server
        if-no-files-found: 'error'

    - name: Upload lldb-server for Android arm32
      uses: actions/upload-artifact@v4
      with:
        name: lldb-server-arm32-${{ github.run_id }}
        path: build-armeabi-v7a/out/bin/lldb-server
        if-no-files-found: 'error'

    - name: Upload lldb-server for Android x86_64
      uses: actions/upload-artifact@v4
      with:
        name: lldb-server-x86_64-${{ github.run_id }}
        path: build-x86_64/out/bin/lldb-server
        if-no-files-found: 'error'




